### ISSUE TITLE
[FEATURE] [TOC] Auto wrap exceesively long heading

### ISSUE THREAD

**Issue by farhan443** [uPagge/uBlogger#40] opened 2021-02-16 11:00 UTC
### Target
Wide-screen TOC (The one displayed at top-right)

### Current behavior
If the heading is too long, the TOC will overflow the x-axis; creating a horizontal scrollbar; making the heading unreadable unless you use the scrollbar.  

#### Screenshot
![Screenshot_20210216_175748](https://user-images.githubusercontent.com/77048921/108053854-87b76500-7080-11eb-9d2f-42aa8c5320d2.png)

### Describe the feature you want

It would be better if the TOC automatically wrap the exceesive characters into a new line. That way, we don't have to use horizontal scrollbar to read the TOC.

**Comment by f-s** [comment] 2021-02-18 15:56
I wonder why that is: Its actually working in the original LoveIt theme ...

**Comment by uPagge** [comment] 2021-02-18 19:14
@f-s I made changes to the design, which unfortunately affected the js script for calculating this mechanism. Until the hands reached the point of correction.

**Comment by f-s** [comment] 2021-02-19 08:25
Is there a way to do this without JS, like using this CSS only:

https://css-tricks.com/a-complete-guide-to-calc-in-css/

I suggest this because, the page repaints - during page load - to do the TOC size adjustment, which not very good design 😞

**Comment by uPagge** [comment] 2021-02-19 15:27
I will study how free time will appear, or even better if you can do PR on this topic :)

I don't really understand what "not very good design" means, quite a tepical solution for this problem

**Comment by uPagge** [comment] 2021-03-03 20:09
@f-s @farhan443 

![изображение](https://user-images.githubusercontent.com/40397740/109865676-64420c00-7c75-11eb-80dc-270b5056f87e.png)

you can check if the problem is observed in the dev branch, apparently not

**Comment by uPagge** [comment] 2021-03-16 17:00
Since I don't have a problem, I close this issue. If the problem is still relevant, please let me know.

**Closed by uPagge** 2021-03-16 17:00 UTC
Labels: bug, fixed in dev
