### ISSUE TITLE
[BUG] Layout problem

### ISSUE THREAD

**Issue by 50bhan** [uPagge/uBlogger#3] opened 2020-12-23 15:38 UTC
### Describe the bug
Hi, Thank you for your work on this amazing theme. I have a problem with the new front matter. When I open a post page, I see a lot of white space in the right section. Look at the below image:

### Screenshot
![Screenshot_2020-12-23_18-56-20](https://user-images.githubusercontent.com/36772278/103012741-45c2e480-4551-11eb-85dd-725fe3bbe9b9.png)

### Build Environment
- OS: [Ubuntu]
- Theme version/commit [1.1.X]
- Hugo version [v0.79.1/extended]

### Preview Environment
- OS: [e.g. Windows 10, macOS, Ubuntu, iOS, Android]
- Browser [e.g. Chrome, Safari, Firefox]

### Additional Information
I have this problem on a wide monitor with high resolution (30 inches - 2560 * 1080). And the problem exists even when I'm visiting the demo site.

**Comment by uPagge** [comment] 2020-12-23 16:17
Hi

Yes, the problem is known, it will be fixed in the next branch.

Thanks for the bug report :)

**Comment by uPagge** [comment] 2020-12-30 14:31
Fixed in version 1.2.0

**Closed by uPagge** 2020-12-30 14:31 UTC
Labels: bug

**Comment by 50bhan** [comment] 2020-12-30 14:49
Great! Thanks. :slightly_smiling_face:
